### Config for dict_trainer ###

notifications:
  interval: 50
  duration: 10
  verbose : True

account_data:
  user: tiptob
  pass: tiptob

remote_paths:
- http://deen.my.dict.cc/export/746615/EN-DE-16439.txt
- http://deen.my.dict.cc/export/710362/EN-DE-16606.txt
- http://deen.my.dict.cc/export/731190/EN-DE-16653.txt
- http://deen.my.dict.cc/export/706790/EN-DE-16683.txt
- http://deen.my.dict.cc/export/706698/EN-DE-16710.txt
# - http://dade.my.dict.cc/export/840202/DE-DA-11249.txt
# - http://denl.my.dict.cc/export/853312/NL-DE-11289.txt

source_paths:
- /home/tobi/Orga/autodidact/history.txt
# - /home/tobi/Orga/dict.cc/Abstracta.txt
# - /home/tobi/Orga/dict.cc/Colloquials.txt
# - /home/tobi/Orga/dict.cc/Concreta.txt
# - /home/tobi/Orga/dict.cc/Phrases.txt
# - /home/tobi/Orga/dict.cc/Miscellaneous.txt
# - /home/tobi/Orga/dict.cc/Dansk.txt
# - /home/tobi/Orga/dict.cc/Nederlands.txt
